import java.util.HashMap;
import java.util.Map;

public class Day2 {

    private static String input = "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Z\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "A Y\n" +
            "C Y\n" +
            "C Y\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "B X\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A Y\n" +
            "C X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A Y\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "A Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "C X\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "A Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "B X\n" +
            "A Z\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C X\n" +
            "B X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "C X\n" +
            "B X\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "B X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Y\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "B X\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "A Z\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B X\n" +
            "A Z\n" +
            "B Y\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "C Z\n" +
            "A Y\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Y\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "B X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "C Y\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "B Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Y\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "C Z\n" +
            "B X\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B X\n" +
            "A Y\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "A Y\n" +
            "A Y\n" +
            "B Y\n" +
            "C X\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A Y\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "B X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A Y\n" +
            "A Y\n" +
            "B Y\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Y\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "A Y\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "C X\n" +
            "A Y\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Y\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "A Y\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "A Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B X\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "A Z\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "B X\n" +
            "C X\n" +
            "A Y\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "A Y\n" +
            "A Y\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "A Y\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "B X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "A Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "A Y\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "C Z\n" +
            "A Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A Y\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B X\n" +
            "B X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "B Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "B X\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "B Z\n" +
            "B X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "A Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "A Y\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "B X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Y\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C Z\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Y\n" +
            "B Z\n" +
            "A Y\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Y\n" +
            "B X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "C Y\n" +
            "C Y\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "C X\n" +
            "A Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "B X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "A X\n" +
            "C Y\n" +
            "A Y\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "B X\n" +
            "C X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A Y\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "A Y\n" +
            "B Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "A X\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "A Y\n" +
            "B Z\n" +
            "B X\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "C Y\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "B Z\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "A Y\n" +
            "B Y\n" +
            "C Z\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "A X\n" +
            "A Y\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "C X\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "B Z\n" +
            "A Y\n" +
            "A Y\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "B Z\n" +
            "A Y\n" +
            "C Z\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "B Z\n" +
            "B Y\n" +
            "A X\n" +
            "C X\n" +
            "C X\n" +
            "A Y\n" +
            "A Y\n" +
            "A X\n" +
            "B X\n" +
            "B Z\n" +
            "B Y\n" +
            "B Y\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Y\n" +
            "C X\n" +
            "B Z\n" +
            "C Z\n" +
            "A Y\n" +
            "C Y\n" +
            "A X\n" +
            "B Z\n" +
            "A X\n" +
            "C Y\n" +
            "B Z\n" +
            "B Y\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C Z\n" +
            "B Z\n" +
            "B Z\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Z\n" +
            "C X\n" +
            "A Y\n" +
            "A Y\n" +
            "B Z\n" +
            "C Z\n" +
            "B Y\n" +
            "C X\n" +
            "C X\n" +
            "A Z\n" +
            "C Z\n" +
            "A X\n" +
            "A X\n" +
            "C X\n" +
            "A Y\n" +
            "C X\n" +
            "A X\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "A Y\n" +
            "C X\n" +
            "C Z\n" +
            "A X\n" +
            "C X\n" +
            "B Y\n" +
            "B Z\n" +
            "B Z\n" +
            "A Y\n" +
            "C Z\n" +
            "C X\n" +
            "C X\n" +
            "B Z\n" +
            "B Z\n" +
            "C X\n" +
            "B Y\n" +
            "A X\n" +
            "B Y\n" +
            "A X\n" +
            "A X\n" +
            "C Y\n" +
            "B X\n" +
            "C X\n" +
            "A Z\n" +
            "A Z\n" +
            "A X\n" +
            "C Z\n" +
            "C Y\n" +
            "C Z\n" +
            "C Y";
    private static Map<String, Integer> shapeToPointMap = new HashMap<>();

    static {
        shapeToPointMap.put("A", 1); // stein
        shapeToPointMap.put("B", 2); // papier
        shapeToPointMap.put("C", 3); // schere

        shapeToPointMap.put("X", 1); // stein
        shapeToPointMap.put("Y", 2); // papier
        shapeToPointMap.put("Z", 3); // schere
    }

    public static void main(String[] args) {

        int totalScore = 0;
        String[] games = input.split("\\R");

        for (String game : games) {
            String[] shapes = game.split("\\s");
            int score = getScore(shapes[0], shapes[1]);
            totalScore += score;
        }

        System.out.println(totalScore);

        int totalScore2 = 0;
        for (String game : games) {
            String[] shapeAndResult = game.split("\\s");
            int score = getScore(shapeAndResult[0], getShapeForDesiredResult(shapeAndResult[0], shapeAndResult[1]));
            totalScore2 += score;
        }

        System.out.println(totalScore2);

    }

    private static int getScore(String shape1, String shape2) {

        int score = shapeToPointMap.get(shape2);

        if (shape1.equals("C") && shape2.equals("X")) return score + 6;
        if (shape1.equals("A") && shape2.equals("Z")) return score;

        int shape1Points = shapeToPointMap.get(shape1.toUpperCase());
        int shape2Points = shapeToPointMap.get(shape2.toUpperCase());

        if (shape1Points == shape2Points) return score + 3;
        if (shape1Points > shape2Points) return score;
        return score + 6;
    }

    private static String getShapeForDesiredResult(String shape1, String result) {
        if (shape1.equals("A")) {
            if (result.equals("X")) return "Z";
            if (result.equals("Y")) return "X";
            return "Y";
        }

        if (shape1.equals("B")) {
            if (result.equals("X")) return "X";
            if (result.equals("Y")) return "Y";
            return "Z";
        }

        // shape1==C
        if (result.equals("X")) return "Y";
        if (result.equals("Y")) return "Z";
        return "X";
    }
}
